import type { Hono } from 'hono'
import { z } from 'zod'
import type { OrganizationRepository } from '@ecc/database'
import { BriefNotFoundError, BriefValidationError, type BriefPreference, type BriefSchedule, type BriefType, type OperationalBrief } from '@ecc/domain'
import type { BriefEngine } from '@ecc/event-engine'

const settingsSchema=z.object({enabled:z.boolean().optional(),localTime:z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/).optional(),recipient:z.string().trim().min(10).max(30).nullable().optional()}).refine(v=>Object.keys(v).length>0,{message:'At least one setting is required'})
const generateSchema=z.object({referenceDate:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),idempotencyKey:z.string().trim().min(1).max(160).optional(),deliver:z.boolean().default(false),recipient:z.string().trim().min(10).max(30).optional()}).optional()
const briefTypeSchema=z.enum(['daily','d_minus_1'])

export function registerBriefRoutes(app:Hono,organizations:OrganizationRepository,engine:BriefEngine):void{
  // Feature 14 compatibility routes: these always refer to the daily schedule.
  app.get('/api/v1/briefs/settings',async c=>{const ctx=await organizationContext(c,organizations);if('response'in ctx)return ctx.response;return c.json({data:serializePreference(await engine.getPreference(ctx.organization.id))})})
  app.post('/api/v1/briefs/settings',async c=>{const ctx=await organizationContext(c,organizations);if('response'in ctx)return ctx.response;const parsed=settingsSchema.safeParse(await c.req.json().catch(()=>null));if(!parsed.success)return c.json({error:{code:'VALIDATION_ERROR',message:'Invalid daily brief settings',issues:parsed.error.issues}},400);try{return c.json({data:serializePreference(await engine.configurePreference({organizationId:ctx.organization.id,...parsed.data,updatedBySender:'api'}))})}catch(error){return mapError(c,error)}})

  // Generic schedules, introduced by Feature 15.
  app.get('/api/v1/briefs/schedules',async c=>{const ctx=await organizationContext(c,organizations);if('response'in ctx)return ctx.response;const values=await Promise.all((['daily','d_minus_1'] as BriefType[]).map(type=>engine.getSchedule(ctx.organization.id,type)));return c.json({data:values.map(serializeSchedule)})})
  app.get('/api/v1/briefs/schedules/:type',async c=>{const ctx=await organizationContext(c,organizations);if('response'in ctx)return ctx.response;const parsed=briefTypeSchema.safeParse(c.req.param('type'));if(!parsed.success)return c.json({error:{code:'INVALID_BRIEF_TYPE',message:'Unsupported brief type'}},400);return c.json({data:serializeSchedule(await engine.getSchedule(ctx.organization.id,parsed.data))})})
  app.post('/api/v1/briefs/schedules/:type',async c=>{const ctx=await organizationContext(c,organizations);if('response'in ctx)return ctx.response;const type=briefTypeSchema.safeParse(c.req.param('type'));if(!type.success)return c.json({error:{code:'INVALID_BRIEF_TYPE',message:'Unsupported brief type'}},400);const parsed=settingsSchema.safeParse(await c.req.json().catch(()=>null));if(!parsed.success)return c.json({error:{code:'VALIDATION_ERROR',message:'Invalid brief schedule settings',issues:parsed.error.issues}},400);try{return c.json({data:serializeSchedule(await engine.configureSchedule({organizationId:ctx.organization.id,type:type.data,...parsed.data,updatedBySender:'api'}))})}catch(error){return mapError(c,error)}})

  app.get('/api/v1/briefs/today',async c=>{const ctx=await organizationContext(c,organizations);if('response'in ctx)return ctx.response;try{return c.json({data:serializeBrief(await engine.getToday(ctx.organization.id))})}catch(error){return mapError(c,error)}})
  app.post('/api/v1/briefs/generate',async c=>{const ctx=await organizationContext(c,organizations);if('response'in ctx)return ctx.response;const parsed=generateSchema.safeParse(await c.req.json().catch(()=>undefined));if(!parsed.success)return c.json({error:{code:'VALIDATION_ERROR',message:'Invalid brief generation payload',issues:parsed.error.issues}},400);const body=parsed.data??{deliver:false};try{const result=await engine.generateDaily({organizationId:ctx.organization.id,triggerType:'manual',triggerKey:`manual:${body.idempotencyKey??crypto.randomUUID()}`,...(body.referenceDate?{referenceDate:body.referenceDate}:{}),requestDelivery:body.deliver,recipient:body.recipient??null,generatedBySender:'api'});return c.json({data:{brief:serializeBrief(result.brief),duplicate:result.duplicate}},result.duplicate?200:201)}catch(error){return mapError(c,error)}})

  app.get('/api/v1/events/:eventId/briefs/d-minus-1',async c=>{const ctx=await organizationContext(c,organizations);if('response'in ctx)return ctx.response;const eventId=validEventId(c);if(eventId instanceof Response)return eventId;try{return c.json({data:serializeBrief(await engine.getDMinus1(ctx.organization.id,eventId))})}catch(error){return mapError(c,error)}})
  app.post('/api/v1/events/:eventId/briefs/d-minus-1/generate',async c=>{const ctx=await organizationContext(c,organizations);if('response'in ctx)return ctx.response;const eventId=validEventId(c);if(eventId instanceof Response)return eventId;const parsed=generateSchema.safeParse(await c.req.json().catch(()=>undefined));if(!parsed.success)return c.json({error:{code:'VALIDATION_ERROR',message:'Invalid D-1 generation payload',issues:parsed.error.issues}},400);const body=parsed.data??{deliver:false};try{const result=await engine.generateDMinus1({organizationId:ctx.organization.id,eventId,triggerType:'manual',triggerKey:`manual:d_minus_1:${eventId}:${body.idempotencyKey??crypto.randomUUID()}`,...(body.referenceDate?{referenceDate:body.referenceDate}:{}),requestDelivery:body.deliver,recipient:body.recipient??null,generatedBySender:'api'});return c.json({data:{brief:serializeBrief(result.brief),duplicate:result.duplicate}},result.duplicate?200:201)}catch(error){return mapError(c,error)}})
  app.get('/api/v1/events/:eventId/briefs/d-minus-1/history',async c=>{const ctx=await organizationContext(c,organizations);if('response'in ctx)return ctx.response;const eventId=validEventId(c);if(eventId instanceof Response)return eventId;const rows=await engine.listDMinus1(ctx.organization.id,eventId,numberQuery(c.req.query('limit'),30,1,100));return c.json({data:rows.map(serializeBrief)})})

  app.get('/api/v1/briefs',async c=>{const ctx=await organizationContext(c,organizations);if('response'in ctx)return ctx.response;const type=c.req.query('type');const limit=numberQuery(c.req.query('limit'),30,1,100);if(type==='d_minus_1')return c.json({data:(await engine.listDMinus1(ctx.organization.id,undefined,limit)).map(serializeBrief)});return c.json({data:(await engine.list(ctx.organization.id,limit)).map(serializeBrief)})})
  app.get('/api/v1/briefs/:briefId',async c=>{const ctx=await organizationContext(c,organizations);if('response'in ctx)return ctx.response;const id=c.req.param('briefId');if(!z.uuid().safeParse(id).success)return c.json({error:{code:'INVALID_BRIEF_ID',message:'briefId must be a UUID'}},400);try{return c.json({data:serializeBrief(await engine.get(ctx.organization.id,id))})}catch(error){return mapError(c,error)}})
}

async function organizationContext(c:any,organizations:OrganizationRepository):Promise<any>{const organizationId=c.req.header('x-organization-id');if(!organizationId||!z.uuid().safeParse(organizationId).success)return{response:c.json({error:{code:'INVALID_ORGANIZATION_ID',message:'A valid x-organization-id is required'}},400)};const organization=await organizations.findById(organizationId);return organization?{organization}:{response:c.json({error:{code:'ORGANIZATION_NOT_FOUND',message:'Organization not found'}},404)}}
function validEventId(c:any):string|Response{const id=c.req.param('eventId');return z.uuid().safeParse(id).success?id:c.json({error:{code:'INVALID_EVENT_ID',message:'eventId must be a UUID'}},400)}
function serializePreference(value:BriefPreference){return{...value,createdAt:value.createdAt.toISOString(),updatedAt:value.updatedAt.toISOString()}}
function serializeSchedule(value:BriefSchedule){return{...value,createdAt:value.createdAt.toISOString(),updatedAt:value.updatedAt.toISOString()}}
function serializeBrief(value:OperationalBrief){return{...value,generatedAt:value.generatedAt.toISOString(),supersededAt:value.supersededAt?.toISOString()??null,deliveryRequestedAt:value.deliveryRequestedAt?.toISOString()??null}}
function mapError(c:any,error:unknown){if(error instanceof BriefNotFoundError)return c.json({error:{code:error.code,message:error.message}},404);if(error instanceof BriefValidationError)return c.json({error:{code:error.code,message:error.message}},400);throw error}
function numberQuery(value:string|undefined,fallback:number,min:number,max:number){const n=Number.parseInt(value??'',10);return Number.isInteger(n)&&n>=min?Math.min(n,max):fallback}
