import type { Hono } from 'hono'
import { z } from 'zod'
import type { OrganizationRepository } from '@ecc/database'
import { BriefNotFoundError, BriefValidationError, type BriefPreference, type DailyBrief } from '@ecc/domain'
import type { BriefEngine } from '@ecc/event-engine'

const settingsSchema=z.object({enabled:z.boolean().optional(),localTime:z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/).optional(),recipient:z.string().trim().min(10).max(30).nullable().optional()}).refine(v=>Object.keys(v).length>0,{message:'At least one setting is required'})
const generateSchema=z.object({referenceDate:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),idempotencyKey:z.string().trim().min(1).max(160).optional(),deliver:z.boolean().default(false),recipient:z.string().trim().min(10).max(30).optional()}).optional()

export function registerBriefRoutes(app:Hono,organizations:OrganizationRepository,engine:BriefEngine):void{
  app.get('/api/v1/briefs/settings',async c=>{const ctx=await organizationContext(c,organizations);if('response'in ctx)return ctx.response;return c.json({data:serializePreference(await engine.getPreference(ctx.organization.id))})})
  app.post('/api/v1/briefs/settings',async c=>{const ctx=await organizationContext(c,organizations);if('response'in ctx)return ctx.response;const parsed=settingsSchema.safeParse(await c.req.json().catch(()=>null));if(!parsed.success)return c.json({error:{code:'VALIDATION_ERROR',message:'Invalid daily brief settings',issues:parsed.error.issues}},400);try{return c.json({data:serializePreference(await engine.configurePreference({organizationId:ctx.organization.id,...parsed.data,updatedBySender:'api'}))})}catch(error){return mapError(c,error)}})
  app.get('/api/v1/briefs/today',async c=>{const ctx=await organizationContext(c,organizations);if('response'in ctx)return ctx.response;try{return c.json({data:serializeBrief(await engine.getToday(ctx.organization.id))})}catch(error){return mapError(c,error)}})
  app.post('/api/v1/briefs/generate',async c=>{const ctx=await organizationContext(c,organizations);if('response'in ctx)return ctx.response;const parsed=generateSchema.safeParse(await c.req.json().catch(()=>undefined));if(!parsed.success)return c.json({error:{code:'VALIDATION_ERROR',message:'Invalid brief generation payload',issues:parsed.error.issues}},400);const body=parsed.data??{deliver:false};try{const result=await engine.generateDaily({organizationId:ctx.organization.id,triggerType:'manual',triggerKey:`manual:${body.idempotencyKey??crypto.randomUUID()}`,...(body.referenceDate?{referenceDate:body.referenceDate}:{}),requestDelivery:body.deliver,recipient:body.recipient??null,generatedBySender:'api'});return c.json({data:{brief:serializeBrief(result.brief),duplicate:result.duplicate}},result.duplicate?200:201)}catch(error){return mapError(c,error)}})
  app.get('/api/v1/briefs',async c=>{const ctx=await organizationContext(c,organizations);if('response'in ctx)return ctx.response;const rows=await engine.list(ctx.organization.id,numberQuery(c.req.query('limit'),30,1,100));return c.json({data:rows.map(serializeBrief)})})
  app.get('/api/v1/briefs/:briefId',async c=>{const ctx=await organizationContext(c,organizations);if('response'in ctx)return ctx.response;const id=c.req.param('briefId');if(!z.uuid().safeParse(id).success)return c.json({error:{code:'INVALID_BRIEF_ID',message:'briefId must be a UUID'}},400);try{return c.json({data:serializeBrief(await engine.get(ctx.organization.id,id))})}catch(error){return mapError(c,error)}})
}

async function organizationContext(c:any,organizations:OrganizationRepository):Promise<any>{const organizationId=c.req.header('x-organization-id');if(!organizationId||!z.uuid().safeParse(organizationId).success)return{response:c.json({error:{code:'INVALID_ORGANIZATION_ID',message:'A valid x-organization-id is required'}},400)};const organization=await organizations.findById(organizationId);return organization?{organization}:{response:c.json({error:{code:'ORGANIZATION_NOT_FOUND',message:'Organization not found'}},404)}}
function serializePreference(value:BriefPreference){return{...value,createdAt:value.createdAt.toISOString(),updatedAt:value.updatedAt.toISOString()}}
function serializeBrief(value:DailyBrief){return{...value,generatedAt:value.generatedAt.toISOString(),supersededAt:value.supersededAt?.toISOString()??null,deliveryRequestedAt:value.deliveryRequestedAt?.toISOString()??null}}
function mapError(c:any,error:unknown){if(error instanceof BriefNotFoundError)return c.json({error:{code:error.code,message:error.message}},404);if(error instanceof BriefValidationError)return c.json({error:{code:error.code,message:error.message}},400);throw error}
function numberQuery(value:string|undefined,fallback:number,min:number,max:number){const n=Number.parseInt(value??'',10);return Number.isInteger(n)&&n>=min?Math.min(n,max):fallback}
