import type { Hono } from 'hono'
import { z } from 'zod'
import type { OrganizationRepository } from '@ecc/database'
import { DependencyConflictError, DependencyNotFoundError, DependencyValidationError, type DependencyImpact } from '@ecc/domain'
import type { DependencyEngine } from '@ecc/event-engine'

const decisionSchema=z.object({sender:z.string().min(2).max(160)})
export function registerDependencyRoutes(app:Hono,organizations:OrganizationRepository,engine:DependencyEngine):void{
  app.get('/api/v1/dependencies',async(c)=>{const ctx=await organizationContext(c,organizations);if('response'in ctx)return ctx.response;const eventId=optionalUuid(c.req.query('eventId'));if(eventId instanceof Response)return eventId;const proposalId=optionalUuid(c.req.query('proposalId'));if(proposalId instanceof Response)return proposalId;const status=enumQuery(c.req.query('status'),['open','applied','resolved','dismissed']);if(status==='__invalid')return c.json({error:{code:'INVALID_STATUS',message:'Unsupported dependency status'}},400);const action=enumQuery(c.req.query('action'),['suggest_update','review']);if(action==='__invalid')return c.json({error:{code:'INVALID_ACTION',message:'Unsupported dependency action'}},400);const type=enumQuery(c.req.query('type'),['task_due_date','milestone_due_date','vendor_schedule','vendor_reconfirmation','guest_capacity_review','venue_logistics_review','manual_schedule_review']);if(type==='__invalid')return c.json({error:{code:'INVALID_DEPENDENCY_TYPE',message:'Unsupported dependency type'}},400);const limit=Number.parseInt(c.req.query('limit')??'50',10);const values=await engine.list({organizationId:ctx.organization.id,...(eventId?{eventId}:{}),...(proposalId?{proposalId}:{}),...(status?{status:status as any}:{}),...(action?{action:action as any}:{}),...(type?{dependencyType:type as any}:{}),limit});return c.json({data:values.map(serialize)})})
  app.get('/api/v1/dependencies/:id',async(c)=>withId(c,organizations,async(org,id)=>c.json({data:serialize(await engine.get(org,id))})))
  app.post('/api/v1/dependencies/:id/apply',async(c)=>decision(c,organizations,engine,'apply'))
  app.post('/api/v1/dependencies/:id/resolve',async(c)=>decision(c,organizations,engine,'resolve'))
  app.post('/api/v1/dependencies/:id/dismiss',async(c)=>decision(c,organizations,engine,'dismiss'))
  app.post('/api/v1/change-proposals/:id/dependencies/apply-suggestions',async(c)=>{const ctx=await organizationContext(c,organizations);if('response'in ctx)return ctx.response;const id=c.req.param('id');if(!z.uuid().safeParse(id).success)return c.json({error:{code:'INVALID_CHANGE_PROPOSAL_ID',message:'id must be a UUID'}},400);const parsed=decisionSchema.safeParse(await c.req.json().catch(()=>null));if(!parsed.success)return c.json({error:{code:'VALIDATION_ERROR',message:'Invalid dependency decision payload',issues:parsed.error.issues}},400);try{const result=await engine.applySuggestionsForProposal({organizationId:ctx.organization.id,proposalId:id,decidedBySender:parsed.data.sender});return c.json({data:{...result,impacts:result.impacts.map(serialize)}})}catch(error){return mapError(c,error)}})
}
async function decision(c:any,organizations:OrganizationRepository,engine:DependencyEngine,kind:'apply'|'resolve'|'dismiss'){const ctx=await organizationContext(c,organizations);if('response'in ctx)return ctx.response;const id=c.req.param('id');if(!z.uuid().safeParse(id).success)return c.json({error:{code:'INVALID_DEPENDENCY_ID',message:'id must be a UUID'}},400);const parsed=decisionSchema.safeParse(await c.req.json().catch(()=>null));if(!parsed.success)return c.json({error:{code:'VALIDATION_ERROR',message:'Invalid dependency decision payload',issues:parsed.error.issues}},400);try{const input={organizationId:ctx.organization.id,impactId:id,decidedBySender:parsed.data.sender};const result=kind==='apply'?await engine.applySuggestion(input):kind==='resolve'?await engine.resolveReview(input):await engine.dismiss(input);return c.json({data:{impact:serialize(result.impact),duplicate:result.duplicate,reply:result.reply}})}catch(error){return mapError(c,error)}}
async function organizationContext(c:any,organizations:OrganizationRepository):Promise<any>{const organizationId=c.req.header('x-organization-id');if(!organizationId||!z.uuid().safeParse(organizationId).success)return{response:c.json({error:{code:'INVALID_ORGANIZATION_ID',message:'A valid x-organization-id is required'}},400)};const organization=await organizations.findById(organizationId);return organization?{organization}:{response:c.json({error:{code:'ORGANIZATION_NOT_FOUND',message:'Organization not found'}},404)}}
async function withId(c:any,organizations:OrganizationRepository,fn:(org:string,id:string)=>Promise<any>){const ctx=await organizationContext(c,organizations);if('response'in ctx)return ctx.response;const id=c.req.param('id');if(!z.uuid().safeParse(id).success)return c.json({error:{code:'INVALID_DEPENDENCY_ID',message:'id must be a UUID'}},400);try{return await fn(ctx.organization.id,id)}catch(error){return mapError(c,error)}}
function mapError(c:any,error:unknown){if(error instanceof DependencyNotFoundError)return c.json({error:{code:error.code,message:error.message}},404);if(error instanceof DependencyConflictError)return c.json({error:{code:error.code,message:error.message}},409);if(error instanceof DependencyValidationError)return c.json({error:{code:error.code,message:error.message}},422);throw error}
function serialize(i:DependencyImpact){return{...i,createdAt:i.createdAt.toISOString(),updatedAt:i.updatedAt.toISOString(),resolvedAt:i.resolvedAt?.toISOString()??null}}
function enumQuery(v:string|undefined,allowed:string[]):string|null|'__invalid'{if(!v)return null;return allowed.includes(v)?v:'__invalid'}
function optionalUuid(v:string|undefined):string|null|Response{if(!v)return null;return z.uuid().safeParse(v).success?v:new Response(JSON.stringify({error:{code:'INVALID_ID',message:'query id must be a UUID'}}),{status:400,headers:{'content-type':'application/json'}})}
